import Header from '@/components/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Amit | Personal Portfoio Web App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`${inter.className} bg-gray-50 text-gray-950 pt-28 sm:pt-36 relative !scroll-smooth`}>
        <div className='bg-[#fbe2e3] absolute top-[-6rem] right-[11rem] h-[31.25rem] w-[32.24rem] -z-10 rounded-full blur-[6rem] sm:w-[68rem]'></div>
        <div className='bg-[#bdb7fb] absolute top-[-1rem] left-[-35rem] h-[31.25rem] w-[50.24rem] -z-10 rounded-full blur-[10rem] sm:w-[68rem] md:left-[-35rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left[-5rem]'></div>
        <Header/>
        {children}
        </body>
    </html>
  )
}
